### ISSUE TITLE
本地打开电子书时章节无法跳转

### ISSUE THREAD

**Issue by HokkaidoLtd** [crifan/crifan.github.io#1]
描述:

我已经成功拉取了整个 [crifan/crifan.github.io](https://github.com/crifan/crifan.github.io) 仓库的文件，以便在无网络的情况下进行阅读。然而，我在尝试本地打开 website 文件夹下的 index.html 文件时，发现章节之间无法跳转。

复现步骤:

	1.	从 GitHub 上克隆或下载仓库。
	2.	打开 website 文件夹。
	3.	使用浏览器直接打开 index.html 文件。
	4.	尝试点击章节链接以进行跳转。

预期行为:

我希望能够顺利地在各个章节之间跳转。

实际行为:

点击章节链接后，页面未能跳转到相应的内容。

**Comment by crifan** [comment]
这个应该是 gitbook（Honkit）的bug，我暂时没能力和精力去解决
你去Honkit中，提交你的bug，估计或许有人帮你解决哈
